In [4]:
import torch
import numpy as np

### 텐서 초기화하기
1. 데이터로부터 직접 생성하기

In [5]:
data = [[1,2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

2. NumPy 배열에서 생성하기

In [6]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
np_array

array([[1, 2],
       [3, 4]])

3. 다른 텐서로부터 생성하기

In [7]:
x_ones = torch.ones_like(x_data) # 속성 유지
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)


tensor([[1, 1],
        [1, 1]])
tensor([[0.9743, 0.6235],
        [0.5871, 0.8089]])


튜플은 텐서의 차원을 나타낸다 (shape 라고 한다)

In [8]:
rand_tensor = torch.rand((2,3)) # 랜덤값 생성
print(rand_tensor)
ones_tensor = torch.ones((3,4)) # 1 생성
print(ones_tensor)
zeros_tensor = torch.zeros((1,1))
print(zeros_tensor)

tensor([[0.1410, 0.6644, 0.7305],
        [0.6638, 0.2652, 0.0733]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.]])


텐서의 속성
- shape : 차원, 모양
- dtype : 자료형
- device : 저장 위치

In [9]:
tensor = torch.rand(3, 4)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.1947, 0.3861, 0.3059, 0.3861],
        [0.1809, 0.5351, 0.2972, 0.5954],
        [0.1965, 0.1519, 0.3817, 0.7593]])
torch.Size([3, 4])
torch.float32
cpu


### 텐서 연산 (Operation)
- 전치(transpose), 인덱싱, 슬라이싱, 수학계산, 선형대수, 샘플링 등 100가지 이상이 있음. 
- 각 연산들은 GPU에서 실행할 수 있다.

In [10]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(tensor.device)

cpu


몇몇 연산들은 Numpy와 비슷하다고 한다.

In [11]:
tensor = torch.ones((3, 4))
tensor[:, 1] = 0  # 1열을 0으로
print(tensor)
tensor[1, :] = 0  # 1 행을 0 으로
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.]])


텐서 합치기

In [15]:
t1 = torch.cat([tensor, tensor, tensor], dim =1) # 1차원, 즉 열을 따라 이어붙임
print(t1)
t2 = torch.cat([tensor, tensor, tensor], dim =0) # 0차원, 즉 행을 따라 이어 붙임.
print(t2)


tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


요소별 곱하기 (element-wise product)
- 동일한 위치끼리 곱하는 연산

In [22]:
t1 = torch.tensor([[1, 2], [3, 4]])
t2 = torch.tensor([[2, 3], [4, 5]])
t3 = t1.mul(t2)
print(t1)
print(t2)
print(t3)

tensor([[1, 2],
        [3, 4]])
tensor([[2, 3],
        [4, 5]])
tensor([[ 2,  6],
        [12, 20]])


행렬곱

In [23]:
t1.matmul(t2)

tensor([[10, 13],
        [22, 29]])

바꿔치기(in-place) 연산
- 원본 데이터를 직접 수정하거나 변경함

In [28]:
print(t1)
t1.add_(5)
print(t1)

tensor([[1, 2],
        [3, 4]])
tensor([[6, 7],
        [8, 9]])


### NumPy 변환(Bridge)
CPU 상의 텐서와 NumPy 배열은 같은 메모리 공간을 공유하기 때문에, 같이 변경된다.

In [31]:
t = torch.ones((5, 5))
n = t.numpy()
print(n)
t.add_(5)
print(n)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]
