In [24]:
import torch
import numpy as np

### 텐서 초기화하기
1. 데이터로부터 직접 생성하기

In [22]:
data = [[1,2], [3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

2. NumPy 배열에서 생성하기

In [52]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
np_array

RuntimeError: Numpy is not available

3. 다른 텐서로부터 생성하기

In [62]:
x_ones = torch.ones_like(x_data) # 속성 유지
print(x_ones)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)


tensor([[1, 1],
        [1, 1]])
tensor([[0.6053, 0.2256],
        [0.2906, 0.8389]])


튜플은 텐서의 차원을 나타낸다 (shape 라고 한다)

In [ ]:
rand_tensor = torch.rand((2,3)) # 랜덤값 생성
print(rand_tensor)
ones_tensor = torch.ones((3,4)) # 1 생성
print(ones_tensor)
zeros_tensor = torch.zeros((1,1))
print(zeros_tensor)

tensor([[0.4987, 0.0650, 0.2952],
        [0.8744, 0.4105, 0.6951]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[0.]])


텐서의 속성
- shape : 차원, 모양
- dtype : 자료형
- device : 저장 위치

In [70]:
tensor = torch.rand(3, 4)
print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.8755, 0.7192, 0.2222, 0.0297],
        [0.6899, 0.3936, 0.4171, 0.2497],
        [0.4927, 0.5435, 0.5250, 0.4668]])
torch.Size([3, 4])
torch.float32
cpu


### 텐서 연산 (Operation)
- 전치(transpose), 인덱싱, 슬라이싱, 수학계산, 선형대수, 샘플링 등 100가지 이상이 있음. 
- 각 연산들은 GPU에서 실행할 수 있다.

In [72]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
print(tensor.device)

cpu


몇몇 연산들은 Numpy와 비슷하다고 한다.

In [76]:
tensor = torch.ones((3, 4))
tensor[:, 1] = 0  # 1열을 0으로
print(tensor)
tensor[1, :] = 0  # 1 행을 0 으로
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.]])
